#pragma kernel CSMain

#include "Assets/FluidSimulation/FluidSimulationLibrary.hlsl"

RWStructuredBuffer<AdvectData> _AdvectDatas;
RWStructuredBuffer<VortexData> _VortexDatas;

int _AdvectDatasLength;

[numthreads(256,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	uint index = id.x;
	if(index >= _AdvectDatasLength) {
		return;
	}

	_AdvectDatas[index] = (AdvectData)0;
	_VortexDatas[index] = (VortexData)0;
}